# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]                
        in_memory:
            memory: 
                users:
                    penart:
                        password: panama
                        roles: [ROLE_ADMIN, ROLE_USER]
        user_db:
            entity:
                class: SmRecordBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer
    
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext                                 
        ITSPS\SmRecordBundle\Entity\User: plaintext
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|bootstrap-3.3.6|jquery-ui-1.11.4)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            anonymous: ~

            form_login: 
                login_path: /login   
                check_path: /login   
            logout:
                path:   /logout
                target: /
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/smrecord/sr, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
